---
version: "3.8"

services:
  helloworld:
    image: quay.io/rocats/helloworld:latest
    container_name: helloworld 
    build:
      context: .
    ports:
      - 8080:8080
    restart: unless-stopped
