---
version: "3.8"

services:
  helloworld:
    image: quay.io/rocats/helloworld:latest
    container_name: helloworld 
    build:
      context: .
      args:
        PYTHON_VERSION: 3.12
    ports:
      - 5000:5000
    restart: unless-stopped
