---
version: "3.8"

services:
  helloworld:
    image: quay.io/rocats/helloworld:latest
    container_name: helloworld 
    build:
      context: .
      args:
        NGINX_UNIT_VERSION: 1.31.1
        PYTHON_VERSION: 3.11
    ports:
      - 8080:80
    restart: unless-stopped
